version: '3.8'
services:
  mysql:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - db1:/var/lib/mysql
  app:
    depends_on:
      - mysql
    build: ./api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ecommerce
      - DB_PORT=3306
    stdin_open: true
    tty: true
#  angular-app:
#    image: frontend:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "4200:4200" # Mapea el puerto 4200 en tu máquina al puerto 80 del contenedor
#    volumes:
#      - ./src:/usr/src/app/src
#      - ./angular.json:/usr/src/app/angular.json
#      - ./tsconfig.json:/usr/src/app/tsconfig.json
#    environment:
#      - NG_ENV=dev # Establece la variable de entorno si es necesario
volumes:
  db1:
